Converting mixins into composables
weavr-io/onvirtual.cards pull request #184
Opened 2024-04-29 16:08 UTC by oleggrech-t

2024-04-29 18:14 UTC, PeterThrels requested changes
Arrow functions can be used as code style in composables.

2024-04-29 18:14 UTC, PeterThrels commented on composables/useAccounts.ts
> +import { useCsv } from './useCsv'
absolute paths please

2024-04-29 18:14 UTC, PeterThrels commented on composables/useCsv.ts
> +    function downloadBlobToCsv(blob) {
arrow functions here?

2024-04-30 07:30 UTC, PeterThrels approved these changes

2024-04-30 07:58 UTC, jasnvella2 approved these changes

2024-05-15 09:44 UTC, gaucj-t approved these changes

2024-05-15 09:44 UTC, merged

2024-05-15 09:45 UTC, PeterThrels approved these changes